FROM gradle:8.9-jdk21 AS builder
WORKDIR /home/gradle/app
COPY --chown=gradle:gradle backend ./backend
WORKDIR /home/gradle/app/backend
RUN gradle clean bootJar -x test

FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=builder /home/gradle/app/backend/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]