blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/jamesmcdonald112/pomodoro/discussions
    about: Please ask and answer questions in GitHub Discussions.