spring:
  application:
    name: backend

  profiles:
    # Default profile when none is specified (safe for local dev)
    active: ${SPRING_PROFILES_ACTIVE:dev}

---

# =============================
# 🧩 DEV (Local H2 Database)
# =============================
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/devdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${SERVER_PORT:8080}

---

# =============================
# 🟢 SUPABASE (Hosted PostgreSQL)
# =============================
spring:
  config:
    activate:
      on-profile: supabase

  datasource:
    driver-class-name: org.postgresql.Driver
    # Always use the ?sslmode=require flag with Supabase
    url: ${SUPABASE_JDBC_URL}
    username: ${SUPABASE_USERNAME}
    password: ${SUPABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8080}

---

# =============================
# 🚀 PROD (Docker / PostgreSQL)
# =============================
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    # Default points to your Docker service `db`
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/appdb}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8080}

---

# =============================
# ⚙️ ACTUATOR & APP METADATA
# =============================
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health", "info" ]

  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    info:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: "${version:0.0.1-SNAPSHOT}"
    description: "Spring + React full-stack backend template"

  build:
    artifact: ${project.artifactId:backend}
    time: ${build.time:unknown}

  git:
    commit:
      id: ${git.commit.id.abbrev:unknown}
    branch: ${git.branch:unknown}