name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Add labels to Dependabot PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: dependencies, automated

      - name: Request reviewers for Dependabot PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: ['jamesmcdonald112']
            })

      - name: Auto-merge patch and minor updates
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          target: minor